spring:
    datasource:
        url: jdbc:mysql://172.30.1.92:3306/moneybug
        username: hum
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8082

mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.moneybug.bug.users.entity
