spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://172.30.1.68:3306/moneybug
    username: hum
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1000  # 최대 풀 크기
      minimum-idle: 1000  # 최소 유효 커넥션 수
      idle-timeout: 600000  # 유휴 커넥션 유지 시간 (기본값: 600000 ms, 10분)
      connection-timeout: 30000  # 커넥션 요청 대기 시간 (기본값: 30000 ms, 30초)
      max-lifetime: 1800000  # 커넥션의 최대 수명 (기본값: 1800000 ms, 30분)
  mustache:
    servlet:
      expose-request-attributes: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dnrgks142@gmail.com
    password: owwibixtmpwevrwh
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connection-timeout: 5000
          write-timeout: 5000
          starttls:
            enable: true
            required: true
          debug: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.moneybug.bug.vo

auth:
  code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

server:
  port: 8082
  servlet:
    session:
      timeout: 90m

logging:
  level:
    com.moneybug.bug: DEBUG
    org.mybatis: DEBUG
    org:
      springframework:
        security: DEBUG
    org.springframework.security: TRACE
    org.springframework.web.client: TRACE

security:
  oauth2:
    client:
      registration:
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          redirect-uri: http://localhost:8082/login/oauth2/code/naver
          authorization-grant-type: authorization_code
          scope:
            - name
            - email
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: http://localhost:8082/login/oauth2/code/google
          authorization-grant-type: authorization_code
          scope:
            - profile
            - email
        kakao:
          client-id: ${KAKAO_CLIENT_ID}
          #client_secret: ARx7tqnIiCWr0R3z4I8JdtMi2lrqud5d
          #client-authentication-method: client_secret_basic
          #redirect-uri: http://localhost:8082/login/oauth2/code/kakao
          #authorization-grant-type: authorization_code
          response_type: code
          scope:
            - profile_nickname
            - profile_image
            - account_email
          client-name: Kakao
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id