spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://192.168.219.102:3306/moneybug
    username: hum
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mustache:
    servlet:
      expose-request-attributes: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dnrgks142@gmail.com
    password: owwibixtmpwevrwh
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connection-timeout: 5000
          write-timeout: 5000
          starttls:
            enable: true
            required: true
          debug: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.moneybug.bug.vo

auth:
  code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

server:
  port: 8082
  servlet:
    session:
      timeout: 90m

logging:
  level:
    com.moneybug.bug: DEBUG
    org.mybatis: DEBUG

security:
  oauth2:
    client:
      registration:
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          redirect-uri: http://localhost:8082/login/oauth2/code/naver
          authorization-grant-type: authorization_code
          scope:
            - name
            - email
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: http://localhost:8082/login/oauth2/code/google
          authorization-grant-type: authorization_code
          scope:
            - profile
            - email
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
