

mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true


spring:
    datasource:
        url: jdbc:mysql://192.168.219.104:3306/moneybug
        username: hum
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8082

logging:
    level:
        com.moneybug.bug: DEBUG
        org.mybatis: DEBUG

