spring:
    datasource:
        url: jdbc:mysql://192.168.219.102:3306/moneybug
        username: hum
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8082
