spring:
    datasource:
        url: jdbc:mysql://localhost:3306/moneybug
        username: root
        password: hyson
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8081

mybatis: 
    mapper-locations: classpath:mapper/**/*.xml 
    configuration:
      map-underscore-to-camel-case: true
    type-aliases-package: com.moneybug.bug.**.vo
